workflows:
  hello-world:
    name: Hello world workflow
    scripts:
      - name: Build for iOS         # Name of the section
        script: xamarin build ios   # The script(s) to be run in that section
